export const events = [
    { name: "2x2", slug: "2x2" },
    { name: "3x3", slug: "3x3" },
    { name: "4x4", slug: "4x4" },
    { name: "5x5", slug: "5x5" },
    { name: "6x6", slug: "6x6" },
    { name: "7x7", slug: "7x7" },
    { name: "3BLD", slug: "3bld" },
    { name: "4BLD", slug: "4bld" },
    { name: "5BLD", slug: "5bld" },
    { name: "MBLD", slug: "mbld" },
    { name: "3x3OH", slug: "3x3oh" },
    { name: "3x3 With Feet", slug: "3x3-with-feet" },
    { name: "Square-1", slug: "square-1" },
    { name: "Pyraminx", slug: "pyraminx" },
    { name: "Megaminx", slug: "megaminx" },
    { name: "Skewb", slug: "skewb" },
    { name: "Clock", slug: "clock" },
    { name: "FMC", slug: "fmc" },
    { name: "2GEN", slug: "2gen" },
    { name: "LSE", slug: "lse" },
    { name: "2BLD", slug: "2bld" },
    { name: "Kilominx", slug: "kilominx" },
    { name: "3x3 Mirror Blocks/Bump", slug: "3x3-mirror-blocks-bump" },
    { name: "Void Cube", slug: "void-cube" },
    { name: "4x4 OH", slug: "4x4-oh" },
    { name: "2x2x3", slug: "2x2x3" },
    { name: "3x3x2", slug: "3x3x2" },
    { name: "3x3x4", slug: "3x3x4" },
    { name: "3x3x5", slug: "3x3x5" },
    { name: "2-3-4 Relay", slug: "2-3-4-relay" },
    { name: "3x3 Relay of 3", slug: "3x3-relay-of-3" },
    { name: "PLL Time Attack", slug: "pll-time-attack" },
    { name: "COLL", slug: "coll" },
    { name: "F2L", slug: "f2l" },
    { name: "Redi Cube", slug: "redi-cube" },
    { name: "Dino Cube", slug: "dino-cube" },
    { name: "8x8", slug: "8x8" },
    { name: "9x9", slug: "9x9" }
] 