"""Add ModeratorReviewRequest

Revision ID: 7d64e9fa8093
Revises: 347361bd5358
Create Date: 2019-05-10 15:40:18.697045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d64e9fa8093'
down_revision = '347361bd5358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_review_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('results_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('isAddressed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['results_id'], ['user_event_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderator_review_request')
    # ### end Alembic commands ###
